seasons_including_nonexistent_episodes:
  -
    id: 1
    title: '鉄人28号ガオ！'
    episodes:
      -
        id: 1
        episode_no: ''
        title: '【無料】金田正太郎危機一髪！'
  -
    id: 2
    title: 'ソードアート・オンライン オルタナティブ ガンゲイル・オンライン'
    episodes:
      -
        id: 1
        episode_no: '#5.5'
        title: 'ルフラン'
  -
    id: 3
    title: '一人之下 羅天大ショウ篇（ラテンタイショウ篇）'
    episodes:
      -
        id: 1
        episode_no: '#0'
        title: '一人之下 羅天大ショウ篇 放送直前スペシャル（１期総集編）'
  -
    id: 4
    title: '立花館To Lieあんぐる'
    episodes:
      -
        id: 1
        episode_no: '第13話'
        title: '特別番組『立花館To Lieあんぐる withエラバレシ』'
  -
    id: 5
    title: 'orange'
    episodes:
      -
        id: 1
        episode_no: '13'
        title: 'LAST　LETTER'
  -
    id: 6
    title: '千銃士'
    episodes:
      -
        id: 1
        episode_no: '第9.5話'
        title: '目指せ絶対高貴！ふたりはNoble ！'

seasons_including_different_title_episodes:
  -
    id: 1
    title: '妖怪アパートの幽雅な日常'
    episodes:
      -
        id: 1
        head:
          episode_no: '第15怪'
          title: '新任教師登場！'
        nico_branch:
          episode_no: '第15怪'
          title: '妖怪アパートの幽雅な日常'
  -
    id: 2
    title: 'ねこねこ日本史 第２期'
    episodes:
      -
        id: 1
        head:
          episode_no: '第47話・第48話'
          title: 'まるっとまとめて、毛利元就！／祝！？ねこねこ日本、開国！'
        nico_branch:
          episode_no: '第47話・第48話'
          title: 'まるっとまとめて、毛利元就！'
  -
    id: 3
    title: 'ダメプリ ANIME CARAVAN'
    episodes:
      -
        id: 1
        head:
          episode_no: '第1話'
          title: 'ダメ王子×登場'
        nico_branch:
          episode_no: '第1話'
          title: 'ダメ王子 × 登場'
  -
    id: 4
    title: 'つうかあ'
    episodes:
      -
        id: 1
        head:
          episode_no: '第5話'
          title: '『Reverse Grid』'
        nico_branch:
          episode_no: '第5話'
          title: '『ReverseGrid』'
  -
    id: 5
    title: '少女終末旅行'
    episodes:
      -
        id: 1
        head:
          episode_no: '第12話'
          title: '「接続」「仲間」'
        nico_branch:
          episode_no: '第12話'
          title: '少女終末旅行'
  -
    id: 6
    title: 'ワンピース チョッパー登場・冬島編'
    episodes:
      -
        id: 1
        head:
          episode_no: '第88話'
          title: '動物<ゾオン>系悪魔の実！チョッパー七段変形'
        nico_branch:
          episode_no: '第88話'
          title: '動物＜ゾオン＞系悪魔の実！チョッパー七段変形'
  -
    id: 7
    title: '妖怪ウォッチ シャドウサイド'
    episodes:
      -
        id: 1
        head:
          episode_no: '第３話'
          title: '略奪魔レッドヘッド'
        nico_branch:
          episode_no: '第３話'
          title: '略奪魔 レッドヘッド'
      -
        id: 2
        head:
          episode_no: '第１４話'
          title: '不動明王邪と天'
        nico_branch:
          episode_no: '第１４話'
          title: '不動明王 邪と天'
  -
    id: 8
    title: 'TVアニメ「ペルソナ５」'
    episodes:
      -
        id: 1
        head:
          episode_no: '#21'
          title: 'You can call me "Noir"'
        nico_branch:
          episode_no: '#21'
          title: 'You can call me ”Noir”'
  -
    id: 9
    title: '君のいる町　OAD'
    episodes:
      -
        id: 1
        head:
          episode_no: ''
          title: '『君のいる町 A town where you live 』 ～黄昏交差点～1 '
        nico_branch:
          episode_no: ''
          title: '『君のいる町 A town where you live 』 ～黄昏交差点～1 '
      -
        id: 2
        head:
          episode_no: ''
          title: '『君のいる町 A town where you live 』 ～黄昏交差点～2'
        nico_branch:
          episode_no: ''
          title: '『君のいる町 A town where you live 』 ～黄昏交差点～2'
      - id: 3
        head:
          episode_no: ''
          title: '『君のいる町 A town where you live 』 ～ウチがきた町～ '
        nico_branch:
          episode_no: ''
          title: '『君のいる町 A town where you live 』 ～ウチがきた町～ '
      - id: 4
        head:
          episode_no: ''
          title: '『君のいる町 A town where you live 』  ～約束の場所で～ '
        nico_branch:
          episode_no: ''
          title: '『君のいる町 A town where you live 』  ～約束の場所で～ '
  - id: 10
    title: 'ストリートファイターⅡV'
    episodes:
      - id: 1
        head:
          episode_no: '第25話'
          title: '死闘<第一章> 壮絶､トリプルバトルコマンド'
        nico_branch:
          episode_no: '第25話'
          title: '死闘＜第一章＞ 壮絶､トリプルバトルコマンド'
      - id: 2
        head:
          episode_no: '第26話'
          title: '死闘<第二章> 力尽きゆく親友の断末魔'
        nico_branch:
          episode_no: '第26話'
          title: '死闘＜第二章＞ 力尽きゆく親友の断末魔'
      - id: 3
        head:
          episode_no: '第27話'
          title: '死闘<第三章> 臨界点､激突する波動エネルギーの極限'
        nico_branch:
          episode_no: '第27話'
          title: '死闘＜第三章＞ 臨界点､激突する波動エネルギーの極限'
      - id: 4
        head:
          episode_no: '第28話'
          title: '死闘<第四章> 君臨者ベガ、その圧倒的破懐力'
        nico_branch:
          episode_no: '第28話'
          title: '死闘＜第四章＞ 君臨者ベガ、その圧倒的破懐力'
  - id: 11
    title: 'TVアニメ「ペルソナ４」'
    episodes:
      - id: 1
        head:
          episode_no: '#13'
          title: 'A Stormy Summer Vacation 1/2'
        nico_branch:
          episode_no: '#13'
          title: 'A Stormy  Summer Vacation 1/2'
      - id: 2
        head:
          episode_no: '#14'
          title: 'A Stormy Summer Vacation 2/2'
        nico_branch:
          episode_no: '#14'
          title: 'A Stormy  Summer Vacation 2/2'
  - id: 12
    title: 'ガイコツ書店員 本田さん'
    episodes:
      - id: 1
        head:
          episode_no: '第8話'
          title: 'A「ホンヤハイイゾ」／B「入っていい棚 だめな棚」／C「それいけ！ アザラシさん～密かなる野望～」'
        nico_branch:
          episode_no: '第8話'
          title: 'A「ホンヤハイイゾ」／B「入っていい棚 だめな棚」／C「それいけ！  アザラシさん～密かなる野望～」'
  - id: 13
    title: 'エリア88'
    episodes:
      - id: 1
        head:
          episode_no: '第3話'
          title: '蒼空のファインダー　Sin&Makoto'
        nico_branch:
          episode_no: '第3話'
          title: '蒼空のファインダー　Sin＆Makoto'
  - id: 14
    title: 'FAIRY TAIL　第49話～第72話'
    episodes:
      - id: 1
        head:
          episode_no: '第51話'
          title: 'LOVE & LUCKY'
        nico_branch:
          episode_no: '第51話'
          title: 'LOVE ＆ LUCKY'
  - id: 15
    title: '残響のテロル'
    episodes:
      - id: 1
        head:
          episode_no: '第2話'
          title: 'CALL & RESPONSE'
        nico_branch:
          episode_no: '第2話'
          title: 'CALL ＆ RESPONSE'
      - id: 2
        head:
          episode_no: '第3話'
          title: 'SEARCH&DESTROY'
        nico_branch:
          episode_no: '第3話'
          title: 'SEARCH＆DESTROY'
      - id: 3
        head:
          episode_no: '第5話'
          title: 'HIDE&SEEK'
        nico_branch:
          episode_no: '第5話'
          title: 'HIDE＆SEEK'
      - id: 4
        head:
          episode_no: '第9話'
          title: 'HIGHS&LOWS'
        nico_branch:
          episode_no: '第9話'
          title: 'HIGHS＆LOWS'
  - id: 16
    title: 'ONE OUTS'
    episodes:
      - id: 1
        head:
          episode_no: '第7話'
          title: '「Trick&Trap」'
        nico_branch:
          episode_no: '第7話'
          title: '「Trick＆Trap」'
  - id: 17
    title: '曇天に笑う＜外伝＞ ～決別、犲の誓い～'
    episodes:
      - id: 1
        head:
          episode_no: 'Chapter.1'
          title: '曇天に笑う<外伝> ～決別、犲の誓い～'
        nico_branch:
          episode_no: 'Chapter.1'
          title: '曇天に笑う＜外伝＞ ～決別、犲の誓い～'
      - id: 2
        head:
          episode_no: 'Chapter.2'
          title: '曇天に笑う<外伝> ～決別、犲の誓い～'
        nico_branch:
          episode_no: 'Chapter.2'
          title: '曇天に笑う＜外伝＞ ～決別、犲の誓い～'
  - id: 18
    title: '曇天に笑う＜外伝＞ ～宿命、双頭の風魔～'
    episodes:
      - id: 1
        head:
          episode_no: 'Chapter.1'
          title: '曇天に笑う<外伝> ～宿命、双頭の風魔～'
        nico_branch:
          episode_no: 'Chapter.1'
          title: '曇天に笑う＜外伝＞ ～宿命、双頭の風魔～'
      - id: 2
        head:
          episode_no: 'Chapter.2'
          title: '曇天に笑う<外伝> ～宿命、双頭の風魔～'
        nico_branch:
          episode_no: 'Chapter.2'
          title: '曇天に笑う＜外伝＞ ～宿命、双頭の風魔～'
      - id: 3
        head:
          episode_no: 'Chapter.3'
          title: '曇天に笑う<外伝> ～宿命、双頭の風魔～'
        nico_branch:
          episode_no: 'Chapter.3'
          title: '曇天に笑う＜外伝＞ ～宿命、双頭の風魔～'
  - id: 19
    title: '曇天に笑う＜外伝＞ ～桜華、天望の架橋～'
    episodes:
      - id: 1
        head:
          episode_no: 'Chapter.1'
          title: '曇天に笑う<外伝> ～桜華、天望の架橋～'
        nico_branch:
          episode_no: 'Chapter.1'
          title: '曇天に笑う＜外伝＞ ～桜華、天望の架橋～'
      - id: 2
        head:
          episode_no: 'Chapter.2'
          title: '曇天に笑う<外伝> ～桜華、天望の架橋～'
        nico_branch:
          episode_no: 'Chapter.2'
          title: '曇天に笑う＜外伝＞ ～桜華、天望の架橋～'
      - id: 3
        head:
          episode_no: 'Chapter.3'
          title: '曇天に笑う<外伝> ～桜華、天望の架橋～'
        nico_branch:
          episode_no: 'Chapter.3'
          title: '曇天に笑う＜外伝＞ ～桜華、天望の架橋～'
  - id: 20
    title: 'プリンセス・プリンシパル'
    episodes:
      - id: 1
        head:
          episode_no: '第5話'
          title: "case7 Bullet & Blade's Ballad"
        nico_branch:
          episode_no: '第5話'
          title: "case7 Bullet ＆ Blade’s Ballad"
  - id: 21
    title: 'ケロロ軍曹 2ndシーズン'
    episodes:
      - id: 1
        head:
          episode_no: '第56話'
          title: "夏美&小雪 テニスのプリンセス であります/ケロロ 侵略日和のさつき晴れ であります"
        nico_branch:
          episode_no: '第56話'
          title: "夏美＆小雪 テニスのプリンセス であります/ケロロ 侵略日和のさつき晴れ であります"
      - id: 2
        head:
          episode_no: '第61話'
          title: "冬樹 謎の転校少女にナニが起こったか? であります/夏美&サブロー 戻れないフ・タ・リ であります"
        nico_branch:
          episode_no: '第61話'
          title: "冬樹 謎の転校少女にナニが起こったか? であります/夏美＆サブロー 戻れないフ・タ・リ であります"
      - id: 3
        head:
          episode_no: '第62話'
          title: "桃華&夏美&モア 怪盗モアピーチサマー であります/ケロロ 必勝!水中大決戦 であります"
        nico_branch:
          episode_no: '第62話'
          title: "桃華＆夏美＆モア 怪盗モアピーチサマー であります/ケロロ 必勝!水中大決戦 であります"
      - id: 4
        head:
          episode_no: '第66話'
          title: "ギロロ 愛の救出大作戦 であります/夏美&小雪 ドッキドッキ初デート であります"
        nico_branch:
          episode_no: '第66話'
          title: "ギロロ 愛の救出大作戦 であります/夏美＆小雪 ドッキドッキ初デート であります"
      - id: 5
        head:
          episode_no: '第67話'
          title: "冬樹&桃華 ひみつのミステリーデート であります/ケロロ なあ､ゲームを作ろうじゃないか であります"
        nico_branch:
          episode_no: '第67話'
          title: "冬樹＆桃華 ひみつのミステリーデート であります/ケロロ なあ､ゲームを作ろうじゃないか であります"
      - id: 6
        head:
          episode_no: '第86話'
          title: "冬樹&夏美 悪魔のすむ日向家 であります/ケロロ なれ!スーパーヒーローに であります"
        nico_branch:
          episode_no: '第86話'
          title: "冬樹＆夏美 悪魔のすむ日向家 であります/ケロロ なれ!スーパーヒーローに であります"
      - id: 7
        head:
          episode_no: '第94話'
          title: "カララ&タルル ペコポンをもらっちゃおう! であります"
        nico_branch:
          episode_no: '第94話'
          title: "カララ＆タルル ペコポンをもらっちゃおう! であります"
      - id: 8
        head:
          episode_no: '第97話'
          title: "桃華 強敵と書いて“とも”と読む であります/ケロロ&冬樹 ふたりで… であります"
        nico_branch:
          episode_no: '第97話'
          title: "桃華 強敵と書いて“とも”と読む であります/ケロロ＆冬樹 ふたりで… であります"
      - id: 9
        head:
          episode_no: '第98話'
          title: "桃華 駆け落ち大作戦 であります/ドロロ&小雪 出会いの記憶 であります"
        nico_branch:
          episode_no: '第98話'
          title: "桃華 駆け落ち大作戦 であります/ドロロ＆小雪 出会いの記憶 であります"
  - id: 22
    title: 'ケロロ軍曹 3rd シーズン'
    episodes:
      - id: 1
        head:
          episode_no: '第134話'
          title: "ケロロ　風邪をひいたらアフレコだ!?　であります／冬樹&クルル　秋葉原を行く　であります"
        nico_branch:
          episode_no: '第134話'
          title: "ケロロ　風邪をひいたらアフレコだ!?　であります／冬樹＆クルル　秋葉原を行く　であります"
  - id: 23
    title: 'ケロロ軍曹 5thシーズン'
    episodes:
      - id: 1
        head:
          episode_no: '第227話'
          title: "ケロロ&夏美 ひとつの部屋 であります"
        nico_branch:
          episode_no: '第227話'
          title: "ケロロ＆夏美 ひとつの部屋 であります"
      - id: 2
        head:
          episode_no: '第229話'
          title: "ケロロ コトバの必殺拳！ であります／サブロー&クルル 静かな戦い であります"
        nico_branch:
          episode_no: '第229話'
          title: "ケロロ コトバの必殺拳！ であります／サブロー＆クルル 静かな戦い であります"

seasons_with_different_title:
  -
    id: 1
    title: 'ReLIFE"完結編"'
    different_titles:
      lineup:
      episode: 'ReLIFE”完結編”'
  -
    id: 2
    title: '犬猫アワー ｢47都道府犬R&にゃ～めん｣'
    different_titles:
      lineup:
      episode: '犬猫アワー ｢47都道府犬R＆にゃ～めん｣'
  -
    id: 3
    title: '戦姫絶唱シンフォギアＸＶ'
    different_titles:
      lineup: '戦姫絶唱シンフォギアXV'
      episode:
