paths:
  fixtures: './spec/fixtures'
seasons_including_nonexistent_episodes:
  -
    id: 1
    title: '愛少女ポリアンナ物語'
    episodes:
      -
        id: 1
        episode_no: ''
        title: 'ニコニコ支店には存在しないエピソード'
seasons_including_different_title_episodes:
  -
    id: 1
    title: 'アイドル事変'
    episodes:
      -
        id: 1
        head:
          episode_no: '事変01'
          title: '私が国会議員になっても'
        nico_branch:
          episode_no: '#01'
          title: '私が市会議員になっても'
seasons_with_different_title:
  -
    id: 1
    title: 'ReLIFE"完結編"'
    different_titles:
      lineup:
      episode: 'ReLIFE”完結編”'
  - id: 2
    title: 'ジャイアント・ロボ THE ANIMATION 外伝 銀鈴 GinRei 素足のGinRei Episode.1 盗まれた戦闘チャイナを捜せ大作戦！！'
    different_titles:
      lineup: 'ジャイアント・ロボ THE ANIMATION 外伝 銀鈴 GinRei  素足のGinRei Episode.1 盗まれた戦闘チャイナを捜せ大作戦！！'
      episode:
  - id: 3
    title: 'ジャイアント・ロボ THE ANIMATION 外伝 銀鈴 GinRei 青い瞳の銀鈴 GinRei with blue eyes'
    different_titles:
      lineup: 'ジャイアント・ロボ THE ANIMATION 外伝 銀鈴 GinRei  青い瞳の銀鈴 GinRei with blue eyes'
      episode:
  - id: 4
    title: '秘密結社 鷹の爪 THE MOVIE～総統は二度死ぬ～'
    different_titles:
      lineup: '秘密結社 鷹の爪  THE MOVIE～総統は二度死ぬ～'
      episode:
  - id: 5
    title: '秘密結社 鷹の爪 THE MOVIE Ⅱ～私を愛した黒烏龍茶～'
    different_titles:
      lineup: '秘密結社 鷹の爪  THE MOVIE Ⅱ～私を愛した黒烏龍茶～'
      episode:
  - id: 6
    title: '秘密結社 鷹の爪 THE MOVIE Ⅲ～http://鷹の爪.jpは永遠に～'
    different_titles:
      lineup: '秘密結社 鷹の爪  THE MOVIE Ⅲ～http://鷹の爪.jpは永遠に～'
      episode:
